- src/ProvidedTypes.fs
The F# compiler doesn't support GetInvokerExpression outputs that contain LetRecursive expression tree nodes, but unlike some other unsupported constructs (e.g. PropertyGet) the ProvidedTypes API doesn't translate these nodes into equivalent nodes that GetInvokerExpression can handle.
This pull request contains an implementation of such a translation.  Unfortunately, the translation does incur some overhead, but this is pretty much unavoidable without proper compiler support for "let rec" nodes.
> Add support for translating away "let rec" expressions within provided member bodies

- nuget/FSharp.TypeProviders.StarterPack.nuspec
Fix to https://github.com/fsprojects/FSharp.TypeProviders.StarterPack/issues/60
> Fixed project URL

- src/ProvidedTypes.fs
http://stackoverflow.com/questions/24065723/how-do-i-create-type-for-array-of-providedtype
> Allow arrays of provided types

- src/ProvidedTypes.fs
> Fix for Obsolete attribute

- .travis.yml
Try updating the Mono version matrix to match github.com/fsharp/fsharp
> update mono version matrix

- src/ProvidedTypesContext.fs
This makes it possible to fix funny bug in F# Data/FsLab.
When replacing one type form `FSharp.Core.DesignTime.dll`, the original code was picking a type from `Deedle.dll` (which inlines CSV parser and contains type with the same name, but not with all the functions). This is just because Deedle appeared earlier in the list of referenced assemblies.
With this fix in, we can create the replacer using:
let bindingContext = 
ProvidedTypesContext.Create(cfg, 
[ "FSharp.Data.DesignTime", "FSharp.Data" ])
This way, types from `FSharp.Data.DesignTime` will only be mapped to types from assembly with a name starting with `FSharp.Data`. If no `assemblyReplacementMap` is specified, it behaves as before and picks type from first assembly that contains it.
/cc @dsyme - I'm merging this to fix F# Data …
> Add way to restrict assembly names in mapping

- paket.dependencies
- paket.lock
- src/ProvidedTypes.fs
- tests/FSharp.TypeProviders.StarterPack.Tests.fsproj
- tests/paket.references
> Wrap type completion in try-finally

- src/AssemblyReader.fs
Used in https://github.com/fsprojects/Paket/pull/1785
> make AssemblyReader compatible with dotnetcore

- src/ProvidedTypes.fs
This fixes the compiler error experienced when compiling with Visual Studio 2015 Update 1 Pro Edition.
> Fix for Issue #113 - 'ExpectedStackState'

- src/ProvidedTypes.fs
> Removed isNull and replaced with = null

- src/ProvidedTypes.fs
- src/ProvidedTypes.fsi
- tests/BasicErasedProvisionTests.fs
Adds some further testing and sanity checking
> adds further testing

- src/ProvidedTypes.fs
- tests/BasicErasedProvisionTests.fs
Add some stack traces to some errors reported by the TPSDK
> add better diagnostics

- .gitignore
- src/ProvidedTypes.fs
- src/ProvidedTypes.fsi
- src/ProvidedTypesTesting.fs
- tests/BasicErasedProvisionTests.fs
Provides a more complete implementation of symbols representing instantiations of generic types
Testing included
> more complete symbol implementation

- src/ProvidedTypes.fs
- tests/BasicErasedProvisionTests.fs
Fix for https://github.com/fsprojects/FSharp.TypeProviders.SDK/issues/162
Test added for teeatment of System.Void
> fix for swagger provider

- src/ProvidedTypes.fs
- tests/BasicErasedProvisionTests.fs
Fix bug https://github.com/fsprojects/FSharp.TypeProviders.SDK/issues/147, and I believe also https://github.com/fsprojects/FSharp.TypeProviders.SDK/issues/164
> fix bug in delayed member creation

- tests/BasicErasedProvisionTests.fs
Add some testing around AllowNullLiteralAttribute on provided types
> add some more testing

- build.fsx
- src/ProvidedTypes.fs
- src/ProvidedTypes.fsi
- src/ProvidedTypesTesting.fs
- tests/BasicGenerativeProvisionTests.fs
Fixes https://github.com/fsprojects/FSharp.TypeProviders.SDK/issues/166
> enable tests on linux

- src/ProvidedTypes.fs
> minor cleanup

- src/ProvidedTypes.fs
- src/ProvidedTypesTesting.fs
- tests/BasicErasedProvisionTests.fs
Fix https://github.com/fsprojects/FSharp.TypeProviders.SDK/issues/188
> fix 188 - Type replacement should apply to static parameter types

- build.fsx
- paket.dependencies
- paket.lock
- src/ProvidedTypesTesting.fs
- tests/BasicErasedProvisionTests.fs
- tests/BasicGenerativeProvisionTests.fs
- tests/GenerativeEnumsProvisionTests.fs
Addresses https://github.com/fsprojects/FSharp.TypeProviders.SDK/issues/190
> add tests for .NET Standard 2.0 and .NET CoreApp 2.0 code generation

- src/ProvidedTypes.fs
@Thorium reports an invalid host of type providers here: https://github.com/fsprojects/FSharp.TypeProviders.SDK/issues/182#issuecomment-356620396
This should help improve diagnostics for this
> Improve diagnostics for invalid host of TP

- src/ProvidedTypes.fs
- tests/BasicErasedProvisionTests.fs
Partial fix for https://github.com/fsprojects/FSharp.TypeProviders.SDK/issues/192
> fix delegate IsSubclassOf

- src/ProvidedTypes.fs
- tests/BasicGenerativeProvisionTests.fs
See https://github.com/fsprojects/FSharp.TypeProviders.SDK/pull/201#discussion_r167988281
> fix generative constructors

- src/ProvidedTypesTesting.fs
Update computation of reference assembly paths for use when testing type providers
> update path computations

- .travis.yml
- build.fsx
- build.sh
- examples/BasicProvider.DesignTime/BasicProvider.DesignTime.fsproj
- examples/BasicProvider.DesignTime/BasicProvider.Provider.fs
- examples/BasicProvider.Tests/BasicProvider.Tests.fs
- examples/BasicProvider.Tests/BasicProvider.Tests.fsproj
- examples/BasicProvider/BasicProvider.Runtime.fs
- examples/BasicProvider/BasicProvider.fsproj
- examples/ComboProvider.Tests/ComboProvider.Tests.fs
- examples/ComboProvider.Tests/ComboProvider.Tests.fsproj
- examples/ComboProvider/ComboProvider.fs
- examples/ComboProvider/ComboProvider.fsproj
- netfx.props
- src/FSharp.TypeProviders.SDK.fsproj
- tests/FSharp.TypeProviders.SDK.Tests.fsproj
Update testing on .NET CLI and Mono to give more complete coverage
> update testing on dotnet CLI

- README.md
> "by string to target" => "by trying to target"

- src/ProvidedTypesTesting.fs
> Remove internal to allow usage without the need to source include or using reflection

- examples/StressProvider.Tests/File1.fs
- examples/StressProvider.Tests/StressProvider.Tests.fs
- examples/StressProvider/StressProvider.fs
- src/ProvidedTypes.fs
- tests/BasicErasedProvisionTests.fs
* Fixes a problem with System.Void through a nasty hack, see also https://github.com/Microsoft/visualfsharp/pull/5621
* Adds full testing for try/finally and try/catch and fixes a bug in code generation of these
> Fix problem with System.Void, and bug with finally generation

- src/ProvidedTypes.fs
- templates/content/basic/.paket/Paket.Restore.targets
This fixes a code generation issue with OptionalAttribute and .NET Core App 2.0 https://github.com/fsprojects/FSharp.TypeProviders.SDK/issues/272
> Fix https://github.com/fsprojects/FSharp.TypeProviders.SDK/issues/272

- .travis.yml
Mono weekly had a bug, it should now be fixed in the nightly channel
> mono weekly/nightly

- src/ProvidedTypes.fs
- src/ProvidedTypes.fsi
Im using this in falanx, it fleshes out the unchecked sdk a little...
> Add NewRecordUnchecked

- .paket/Paket.Restore.targets
- src/ProvidedTypes.fs
> cache return type

- src/ProvidedTypes.fs
- src/ProvidedTypes.fsi
- tests/GeneratedCodeTests.fs
- tests/GeneratedOpTests.fs
Struct tuple and Expr.DefaultValue support for generated types.
> Value types

- tests/ProvidedTypesTesting.fs
fixes https://github.com/fsprojects/FSharp.TypeProviders.SDK/issues/358
> Switch from CodeBase to Location in providedtypestesting

- .github/workflows/pr.yml
- .github/workflows/push.yml
Let's see if this helps the Ubuntu CI...
> Try to fix Ubuntu CI error: "No usable version of libssl was found"

- .config/dotnet-tools.json
> Update tool FSharpLint
