- src/ProvidedTypes.fs
- src/ProvidedTypes.fsi
* Support for AllowNullLiteral (https://github.com/fsharp/FSharpLangDesign/blob/master/FSharp-4.0/NonNullProvidedTypesDesignAndSpec.md)
* Remove HideObjectMethods that din't make sense in ProvidedConstrutor (it's supposed to be only for ProvidedType)
* Support UoMs correctly in EraseType
* Prevent crash in .Name on generic symbols
> Port changes from FSharp.Data

- src/ProvidedTypes.fs
When using `ProvidedTypeBuilder.MakeGenericType` with an interface `BaseType` can be null and a NullReferenceException will be thrown in `convType`.
I'm not sure if we want both changes, please tell me if I should remove one of them.
I noticed this in: https://github.com/fsprojects/FSharp.Configuration/pull/53
> Support interface types in ProvidedTypeBuilder.MakeGenericType.

- src/ProvidedTypes.fs
I don't like warnings in my build output :-).
This is a fairly small change, so I'm going to merge it straight away, but I would still appreciate post-code-review - so if someone can have a look at this and ACK that the change is good, that would be great.
> Remove incomplete pattern matching warnings

- src/ProvidedTypes.fs
- src/ProvidedTypes.fsi
This adds the helpers for the (optional) F# 4.0 support for static parameters on methods
I could separate out the cleanup but I think it's ok to include it here as part of a 4.0-era revision of ProvidedTypes.fs
Cheers
don
> add GetStaticParametersForMethod and general cleanup

- src/ProvidedTypes.fs
- src/ProvidedTypes.fsi
- src/ProvidedTypesContext.fs
- tests/BasicGenerativeProvisionTests.fs
The ProvidedTypes.fs implementation has long been a bit of a mess, because of the growing amount of code for generative type providers.
This extracts out the core of the code generator for quotations, and adds the option of having a ``#if NO_GENERATIVE`` define which removes the support for generative type providers.
This also correctly converts some remaining items to target types, especially ``typeof<Array>`` and friends reported as the base types for provided symbol types.
This cleanup is a preliminary to addressing #82 (cross-targeting generative type providers)
> cleanup and convert types to target

- src/ProvidedTypes.fs
I think this is the right way to fix this, but it would be nice if someone could review. (But I'm going to merge this immediately, so that I can release a new version of F# Data Toolbox.)
> Fix null reference exception!

- src/ProvidedTypesTesting.fs
- `t.BaseType` can be `null`, which was breaking things
- `t.GetMembers()` throws for some reason, but it works with the flags
- I also changed the printing to print `: obj` for compatibility with F# Data
@dsyme I'll merge this directly, but if could have a look that would be great
> Makes TP Testing work for F# Data

- src/FSharp.TypeProviders.StarterPack.fsproj
- src/ProvidedTypesTesting.fs
The additional `printf` makes F# Data build logs pretty much unusable when executed on a CI.
> Fix project file and remove printf

- src/ProvidedTypes.fs
which prevented DLLs from being cleaned on disk in generative type
providers. Fixes #97
> Removed commented File.Delete line

- src/ProvidedTypes.fs
"The nested provided type {typename} is marked as erased and cannot be converted to a generated type. Set 'IsErased' to false on the ProvidedTypeDefinition"
it was missing a space between typename and is.
https://github.com/Microsoft/visualfsharp/pull/1153
> Fix typo in error message

- src/ProvidedTypes.fs
I was looking into how provided types are translated to IL to find out the root cause  of #100 and found that `ProvidedTypeDefinition.IsValueType` returns incorrect values when generated type is an enumeration (base type is `System.Enum`, which is itself is not a value type). 
The PR contains a fix for that (and also resolves #100). 
I don't really have full understanding of why it resolves #100, so I'd still appreciate some explanation.
> Consider genrated types inherited from System.Enum to be value types

- src/ProvidedTypes.fs
All the other prints are commented out so I guess those two are remaining from when the new static parameter where being tested. They are a bit distracting when using Fable as the stdout is used to communicate with another process.
> Comment out debugging prints

- src/ProvidedTypes.fs
- tests/FSharp.TypeProviders.StarterPack.Tests.fsproj
- tests/GenerativeEnumsProvisionTests.fs
This PR contains a slight adjustment to the process of completing generated types (calling `TypeBuilder.CreateType`). It also fixes #102. 
As per [documentation](https://msdn.microsoft.com/en-us/library/system.reflection.emit.typebuilder.createtype(v=vs.110).aspx#Anchor_2), calling `TypeBuilder.CreateType` can trigger `AppDomain.TypeResolve` event in the case when the type being created contains fields of a value type declared as a nested type. But it looks like this event is called each time when type being built contains fields of any generated value type for which `TypeBuilder.CreateType` hasn't been called yet (so not only for nested value types).
> Support of using generated enums by other generated types

- src/ProvidedTypes.fs
- src/ProvidedTypes.fsi
Even if the arguments of a provided method are received as expressions, if you want an actual quotation when accessing the argument, you still need to add the `ReflectedDefinition` attribute to the provided parameter. This PR adds this possibility. A usage example can be seen [here](https://github.com/bazingatechnologies/FSharp.Data.GraphQL/pull/68/commits/c981ba01bc84f50586a582d2e1b304875d97d1a8).
> Add ReflectedDefinitionAttribute to provided methods

- README.md
The current code sample in README.MD is wrong.
The ProvidedTypeDefinition constructor has option typed parameter, therefore the calling of the parameter must add Some and this is in sync with the source code in the TP samples.
For example:
```fsharp
let myType = ctxt.ProvidedTypeDefinition(asm, ns, "MyType", typeof<obj>)
```
Should be:
```fsharp
let myType = ctxt.ProvidedTypeDefinition(asm, ns, "MyType", Some typeof<obj>)
```
> Fix code sample in README.MD to match the code in the sample source code.

- src/ProvidedTypes.fs
The recomputed XML Doc attribute is no longer added to the internal custom attributes collection (after customAttributesOnce has been evaluated), but instead returned as part of the custom attribute array when calling GetCustomAttributesData()
> Fix #46: AddXmlDocComputed is not adding xml doc

- src/ProvidedTypes.fs
See https://github.com/fsharp/fsharp/issues/738 and https://github.com/fsprojects/FSharp.TypeProviders.StarterPack/issues/121
All type providers that need to work with Mono 5.0 should be updated to use this copy
> Fix for Mono 5.0

- src/ProvidedTypesContext.fs
Converting existing code to use ProvidedTypesContext would be easier if this invoke-less constructor would be there.
> For convenience, add also a constructor without invoke-code.

- RELEASE_NOTES.md
- build.fsx
- src/ProvidedTypes.fs
- src/ProvidedTypes.fsi
This PR actually fix issue #127
I did sync parameter names from `fsi` to `fs` file in order to save backward compatibility
but would be nice to have an additional pair of eyes before merge and release
> Parameter names synced (from `fsi` to `fs` file)

- src/ProvidedTypesContext.fs
With old VS everything works fine, but when compiling with dotnet.exe, for whatever reason, FSharp couldn't resolve type: `String.StartsWith(value: char)` vs `String.StartsWith(value: string)`
```
C:\git\FSharp.TypeProviders.StarterPack\src\ProvidedTypesContext.fs(95,20): error FS0041: A unique overload for method 'StartsWith' could not be determined based on type information prior to this program point. A type annotation may be needed. Candidates: String.StartsWith(value: char) : bool, String.StartsWith(value: string) : bool [C:\git\myProj.fsproj]
C:\git\FSharp.TypeProviders.StarterPack\src\ProvidedTypesContext.fs(95,70): error FS0041: A unique overload for method 'StartsWith' could not be determined based on type information prior to this program point. A type annotation may be needed. …
```
> Fix for ProvidedTypesContext.fs when compiling with dotnet.exe

- src/AssemblyReaderReflection.fs
- src/ProvidedTypes.fs
- src/ProvidedTypesContext.fs
- tests/BasicGenerativeProvisionTests.fs
Added a disabled failing test and a comment explaining why generative type providers don't work with ProvidedTypesContext (i.e. why generative type providers can't be cross-targeting yet)
```
// Generative providers don't yet work with ProvidedTypesContext.
// The problem is that the ProvidedTypesContext creates artificial types for things like mscorlib Object
// System.Refelction.Emit can't cope with the existence of such types -  System.Refelction.Emit can only
// write types that refer to the runtime loaded mscorlib.
//
// An alternative may be to use the Abstract IL writer and code generator.  Or Mono Cecil.
```
> add test about generative + cleanup

- .travis.yml
- build.fsx
- build.sh
Trying to work out what's going on on Travis configuration, based on @enricosada recommendations to look at these:
* https://github.com/fsharp/FsAutoComplete/blob/master/.travis.yml
* https://github.com/dotnet/netcorecli-fsc/wiki/.NET-Core-SDK-1.0#using-net-framework-as-targets-framework-the-osxunix-build-fails
> test variations on travis

- README.md
- RELEASE_NOTES.md
- build.fsx
- examples/ErasedWithConstructor.fsx
- examples/StaticProperty.fsx
- src/ProvidedTypes.fs
- src/ProvidedTypes.fsi
- src/ProvidedTypesTesting.fs
- tests/BasicErasedProvisionTests.fs
- tests/BasicGenerativeProvisionTests.fs
- tests/GenerativeEnumsProvisionTests.fs
This implements cross-targeting for generative type providers.
With this PR, a generative type provider now uses a IL binary writer built into the TPSDK (a modified copy of the Abstract IL binary writer) to produce the necessary assembly rather than using Reflection.Emit. This means that the output can match the target binaries of the compilation using the standard translate-to-target technique.
Considerably more testing is needed - this is a new binary writer and is currently only tested by the two small generative type providers in the SDK tests.
You can defined NO_GENERATIVE if you want to reduce the size of a non-generative type provider to remove this functionality.
This should allow generative type providers to target .NET Core, and for generative type providers to be implemented on …
> Retargeting for generative type providers

- src/ProvidedTypes.fs
The generative code for the Swagger type provider was invalid in some cases.
(Swagger is a great stress test for both the type provider SDK in general and generative code in particular)
> fixes for swagger code generation

- build.fsx
- src/ProvidedTypes.fs
- src/ProvidedTypes.fsi
- tests/BasicErasedProvisionTests.fs
- tests/BasicGenerativeProvisionTests.fs
- tests/GenerativeEnumsProvisionTests.fs
The Swagger provider does some interesting things like using one generated type as the base type for other generated types.   This causes lookups on the types implied by the generated assembly before generation is complete.
This PR adjusts the translation implementation of the SDK to allow for this, and adds a specific test case for this
> Additional testing and fixes related to Swagger provider

- examples/StaticProperty.Tests.fsx
- src/ProvidedTypes.fs
- src/ProvidedTypesTesting.fs
- tests/BasicGenerativeProvisionTests.fs
Fixes generative TPs for use in F# interactive and other hosted execution environments that expect the ``ty.Assembly`` object for provided types to be a real reflection-emit/reflection-load assembly
Also adds testing for this case
> fix 152 - Generative TP raises error in F# Interactive when using new SDK

- tests/GenerativeEnumsProvisionTests.fs
We should now be able to enable this test since we no longer use Reflection.Emit. See https://github.com/fsprojects/FSharp.TypeProviders.SDK/issues/123
> enable test on mono

- src/ProvidedTypes.fs
I have encountered the very same error as described in #177 in a different context: checking a project using a TP with FCS running inside an ASP.NET application (both the web application and and the checked project are targeting .NET 4.6).
I have found that a null check on `dllInfo` value inside `ProvidedTypesContext.Create` before using it eliminates this error and I could not find any regression.
> Check if Base property on tcImports indeed exists inside ProvidedTypesContext.Create

- examples/BasicProvider.DesignTime/BasicProvider.Provider.fs
- examples/BasicProvider.Tests/BasicProvider.Tests.fs
- src/ProvidedTypes.fs
- src/ProvidedTypes.fsi
- tests/BasicErasedProvisionTests.fs
I have found this useful in particular to add `[<ReflectedDefinition>]` to a parameter.
> Add ProvidedParameter.AddCustomAttribute

- src/ProvidedTypes.fs
- src/ProvidedTypes.fsi
- src/ProvidedTypesTesting.fs
- tests/BasicErasedProvisionTests.fs
The source assembly set was not being computed using transitive closure
> fix 173 - missing assembly in source assembly set

- src/ProvidedTypes.fs
- tests/BasicErasedProvisionTests.fs
1. The FSharp.Data pull request https://github.com/fsharp/FSharp.Data/pull/1097 shows that incorrect argument names were being created for constructors
2. We don't need new variables and let bindings if argument names are identical
> correct argument names

- README.md
Per https://github.com/Microsoft/visualfsharp/issues/4338, it appears that specifying an explicit list of runtime assemblies is necessary, so we can make that clear here.
> Provide guidance on packaging runtime assemblies

- examples/StressProvider.Tests/File1.fs
- examples/StressProvider.Tests/Program.fs
- examples/StressProvider.Tests/StressProvider.Tests.fs
- examples/StressProvider.Tests/StressProvider.Tests.fsproj
- examples/StressProvider.Tests/xunit.runner.json
- examples/StressProvider/StressProvider.fs
- examples/StressProvider/StressProvider.fsproj
- src/ProvidedTypes.fs
Fixes perf problem #220 
We were quadratic for large collections of members, this makes it linear by saving the resolution of `GetMethods` and `GetProperties`
> fix perf of autocomplete for large member sets

- fsc.props
Since VS 15.6 update, the FSC path is updated to `C:\Program Files (x86)\Microsoft SDKs\F#\10.1\Framework\v4.0\fsc.exe`. This PR adds support to this new Windows path to FSC.
> Add support to new FSC path

- src/ProvidedTypes.fs
- src/ProvidedTypes.fsi
This allows the use of NewUnionCaseUnchecked, also the PR unifies the API so that PropertySetUnchecked has the same signature as PropertySet - `args` being optional.
> Add NewUnionCaseUnchecked, also adjust PropertySetUnchecked to have the same signature as PropertySet

- build.fsx
The testing process can't yet run frameworks in parallel, also was not building Examples cleanly prior to testing
> fix testing process

- src/ProvidedTypes.fs
- tests/BasicGenerativeProvisionTests.fs
Add testing that checks that "this" is available for generative TP constructors, as part of investigating https://github.com/fsprojects/FSharp.TypeProviders.SDK/issues/218
> check 'this' for generative constructors, add try/finally with fixes

- examples/BasicProvider.DesignTime/BasicProvider.Provider.fs
- examples/ComboProvider/ComboProvider.fs
- examples/StressProvider/StressProvider.fs
- src/ProvidedTypes.fs
- src/ProvidedTypes.fsi
This adds a new optional argument to TypeProviderForNamespace for adding the location of the TPDTC as a probing location.  This setting is currently necessary (or an explicit use of RegisterProbingFolder is required) for resolving dependencies whenever TPDTC are loaded into F# .NET Core tooling
> addDefaultProbingLocation

- templates/content/basic/src/MyProvider.DesignTime/MyProvider.DesignTime.fs
This fixes the assembly name for generative provider in assembly map in dotnet template. However, I am not so sure, if the Runtime assembly should be used as a replacement, because I couldn't find information on that. That question was raised when @sergey-tihon fixed some [issues ](https://github.com/sergey-tihon/json-provider/blob/da66be7cd9f38a9c46fde28266cf74c1bf70f3c9/src/JsonProvider.DesignTime/JsonProvider.DesignTime.fs#L20)in my provider and it's strange that it works either way (JsonProivder.Runtime or JsonProvider). [Basic provider](https://github.com/fsprojects/FSharp.TypeProviders.SDK/tree/master/examples) uses the Runtime assembly, though.
@dsyme
> Fix assembly names in map for generative provider template

- src/ProvidedTypes.fs
Something like 
```fsharp
let prop1 = ProvidedProperty("InnerState", typeof<string>, getterCode = fun args -> <@@ "hello" @@>)
myType.AddMember(prop1)
let meth2 = ProvidedMethod("InstanceMethod", [], typeof<string>, isStatic=false, invokeCode = (fun args -> Expr.PropertyGet(args.[0],prop1)))
myType.AddMember(meth2)
```
in a generative type provider has issues in hosted environments. It'll compile fine since the asm only gets generated once but fsi and source checking will fail (particularly if static parameters change). This is due to `ProvidedTypesContext` always returning the first "version" of a given type. The new `invokeCode` will be called but with the wrong type for the `this` parameter resulting in an "incorrect instance type" error. The workaround for source checking would be to …
> Use most recent assembly containing type

- src/ProvidedTypes.fs
This change means that only a ByteFile for the metadata section is kept after cracking DLLs in the ILModuleReader used in type providers.
We should also adjust the PEReader so it doesn't read all bytes, so those are ephemeral
Expected benefit is about 50% reduction in memory usage by TPs built using the TPSDK (since referenced assemblies make up most of the memory usage)
> Read only metadata section

- README.md
Before:
```
A:\LemonadeProvider>.paket\paket.exe pack src\LemonadeProvider.Runtime\paket.template --version 0.0.1
Paket version 5.196.2
Performance:
- Runtime: 539 milliseconds
Paket failed with
-> Unable to create directory A:\LemonadeProvider\src\LemonadeProvider.Runtime\paket.template.
```
After:
```
A:\LemonadeProvider>.paket\paket.exe pack src\LemonadeProvider.Runtime --version 0.0.1
Paket version 5.196.2
Packaging: A:\LemonadeProvider\src\LemonadeProvider.Runtime\paket.template
Wrote: A:\LemonadeProvider\src\LemonadeProvider.Runtime\LemonadeProvider.0.0.1.nupkg
Performance:
- Runtime: 1 second
```
> fix for paket pack command

- src/ProvidedTypes.fs
- src/ProvidedTypes.fsi
- tests/BasicErasedProvisionTests.fs
- tests/FSharp.TypeProviders.SDK.Tests.fsproj
This adds a strong cache for ILModuleReaders instead of a weak cache. While we do a File.ReadAllBytes and it goes on the LOH, they will be long lived so it's appropriate. We do include a last write time to invalidate the cache just in case a user changes it; but they do not change frequently.
> [WIP] Added strong cache for ILModuleReaders

- .paket/Paket.Restore.targets
- build.fsx
- src/ProvidedTypes.fs
- src/ProvidedTypesTesting.fs
This is a possible fix for #297 
The TP config does report the ReferencedAssemblies, but IIRC there were some situations where the F# compiler was not correctly filling in this value.  I've checked the code however and can't see why this would be the case.
Actually, it looks like I might have fixed this in 2016 just forgot to remove the hack fro the TPSDK https://github.com/Microsoft/visualfsharp/pull/1037, or didn't want to remove it since old tooling still needed it.
Anyway, let's see if the TPSDK passes with this in place.
> try use ReferencedAssemblies

- .paket/Paket.Restore.targets
- FSharp.TypeProviders.SDK.sln
- build.fsx
- src/ProvidedTypes.fs
- src/ProvidedTypes.fsi
- tests/AssemblyReaderTests.fs
- tests/BasicErasedProvisionTests.fs
- tests/BasicGenerativeProvisionTests.fs
- tests/FSharp.TypeProviders.SDK.Tests.fsproj
- tests/GenerativeEnumsProvisionTests.fs
- tests/Program.fs
@TIHan This eliminates the long-term memory leak from the IL readers used by each TP implementation by clearing the reader cache every 30 seconds since last access (at the potential cost of re-computing readers).
> clear reader cache in background to prevent leak

- src/ProvidedTypes.fs
When reporting an error of missing type in assembly,
https://github.com/fsprojects/FSharp.TypeProviders.SDK/blob/f97f77ba03a8f91d927ab70259dc91eb8ba02e40/src/ProvidedTypes.fs#L14620
uses implicit `ToString`. This causes mono to crash when trying to use
Reflection to get assembly name. This commit patches it by overriding
`ToString`
> Override `ToString` for `ProvidedAssembly`

- src/ProvidedTypes.fs
@dsyme 
The way we search for System.Object in the SDK is not complete.  On Coreclr when using implementation assemblies the location of System.Object is:
System.Private.CoreLib.dll.
mscorlib.dll, System.Runtime.dll and netstandard.dll all have type forwarders.
When using the FSharp.Data type provider on V 2.2.202 of the dotnet CLI I get this:
````
> #r @"C:\Users\kevinr\.nuget\packages\FSharp.Data\3.0.0\lib\netstandard2.0\FSharp.Data.dll"
-
- open FSharp.Data
-
- // Api Key = 93a2637fe6dad8426d128d5289325ca9
- open FSharp.Data
-
- type Weather = JsonProvider<"http://api.openweathermap.org/data/2.5/weather?id=2172797&APPID=93a2637fe6dad8426d128d5289325ca9">
- let apiUrl = "http://api.openweathermap.org/data/2.5/weather?id=2172797"
- let sf = Weather.Load(apiUrl + …
```
> Fix coreclr search for system.object

- .gitignore
- src/ProvidedTypes.fs
- src/ProvidedTypes.fsi
- tests/FSharp.TypeProviders.SDK.Tests.fsproj
- tests/GenerativeAbstractClassesTests.fs
- tests/GenerativeInterfacesTests.fs
- tests/Script1.fsx
This one is based on previous PR
It is needed to make the WsdlProvider work.
There was a problem when generating the Async methods calls because the Task<ProvidedType> was generated in con convtype using typedef.MakeGenericType(args)... making it a TypeBuilderImplementation Instance that failed on IsAssignableFrom
It should actually be a TypeSymbol2 but the function is at the beginning of the Provided.fs file where this type is not defined yet.
So I introduced a ITypeBuilder interface that enables building GenericTypes, arrays etc that is implemented at the ProvidedTypeBuilder level and passed to previous functions to enable recursive generation 
Once done, it works 👍
> Fix typeconversion

- .github/workflows/main.yml
- src/ProvidedTypes.fs
- src/ProvidedTypes.fsi
- tests/GenerativeEnumsProvisionTests.fs
There was no way to add custom attributes on ProvidedFields yet.
It was required to add XmlEnum attribute on generated Enum fields for the WsdlProvider.
The change is minor (adding the AddCustomAttribute method), and test have been added.
> Add CustomAttributes on fields

- templates/content/basic/src/MyProvider.Runtime/paket.references
Fixes https://github.com/fsprojects/FSharp.TypeProviders.SDK/issues/355
> Don't need to refer to ProvidedTypes.fs at runtime

- src/ProvidedTypes.fs
- tests/BasicErasedProvisionTests.fs
Fixes an issue introduced in https://github.com/fsprojects/FSharp.TypeProviders.SDK/pull/377, where some kinds of provided types could slip past the fallback check.
> Fix MakeGenericType fallback

- src/ProvidedTypes.fs
Found https://github.com/fsprojects/FSharp.TypeProviders.SDK/issues/269 while investigating another problem, so I took it as an opportunity to sync the list with the one from https://github.com/dotnet/fsharp/blob/192b86dbc86bb45b38aa23570486e574ed58c920/src/FSharp.Core/SI.fs
> Update hardcoded units of measure

- .config/dotnet-tools.json
- fsharplint.json
- src/ProvidedTypes.fs
This contains the fixes from PR #397 and also installs FSharpLint as dotnet tool, and uses some sensible ruleset.
The ruleset is basically the standard ruleset minus most of the naming rules, as it seems the ProvidedTypes.fs naming conventions are generally not following the standard F# naming conventions and it's basically too late and pointless to try to fix that.
```
A:\git\FSharp.TypeProviders.SDK> dotnet fsharplint lint src\ProvidedTypes.fs
========== Linting src\ProvidedTypes.fs ==========
========== Finished: 0 warnings ==========
========== Summary: 0 warnings ==========
```
> FSharpLint as .NET tool

- src/ProvidedTypes.fs
Minor code-clean-up things:
- isNull is faster than = null
- Error messages should have some meaningful parameters
- TryGetValue is faster than ContainsKey + lookup
> Fixed FSharpLint code issues

- src/ProvidedTypes.fs
Before this PR, I get:
```
src/ProvidedTypes.fs(7532,15): warning FS3548: Pattern discard is not allowed for union case that takes no data. 
```
> fix: remove warning about patter discard not allowed for union case that takes no data

- src/ProvidedTypes.fs
Currently it seems not supported feature in F#9 and it seems no longer required to build this file. 
It's quite possible that I miss something. Let's see
> Remove AutoOpen from ILTableName

- src/ProvidedTypes.fs
The Type.(=) seems to generate less code than comparing two types directly.
See: https://sharplab.io/#v2:DYLgZgzgNALiCGEC2AfA9gBwKYDsAEAygJ4QxZICwAUNdcFjHjEdgMJpIbwBOAlhGhwFgaAO4AKAJR4AvHnHNsaMAB4wI+DAB8spiyzK1G7ZNo1z9RoqztOPfoIBiiGFN0AVfQDpxMyQv1DdTRNLSg9JVVg0NNzMzMgA
> Faster type comparison

- src/ProvidedTypes.fs
Minor code tweaks:
- The ILArrayBound can be defined as struct-option because it's only an int anyway.
- There is no reason to call reflection methods in a for-loop when none of the reflection parameters actually come from the looped variable.
> Minor tweaks

- src/ProvidedTypes.fs
- src/ProvidedTypes.fsi
It seems F# compiler has ProvidedTypes.fs and ProvidedTypes.fsi in the tests folders.
This PR fixes some typos that are already fixed on that side.
> Some typing corrections (taken from fsharp compiler tests)

- src/ProvidedTypes.fs
1) I noticed that if I had 139 reference assemblies (in a solution memory), I ended up calling the Assembly.Load for 897 times. This is because so many assemblies have the same references like System.Memory, System.Xml, System.Buffers, System.Threading.Tasks.Extensions, ... And the code said "load all reference assemblies". Simple fix: Check already loaded reference assemblies before trying to call the slow Assembly.Load again.
2) The sourceAssembliesTable_ is a ConcurrentDictionary to ensure thread-safety. However, instead of code using it in thread-safe way, it was used by double-lookup. So that is fixed to actually use it properly. (It's role is to be used as a guard to sourceAssemblies_ array, which is manually lazy-loaded from the queue.)
> Reference assembly loading fixes

- src/ProvidedTypes.fs
This fixes the file to compile when using FX_NO_LOCAL_FILESYSTEM.
Fix for #403.
> Build fix for FX_NO_LOCAL_FILESYSTEM

- src/ProvidedTypes.fs
- isNull is inline also in FSharp.Core. It's called in many places.
- Lazy load of ILAssemblyRefs: There is no point in spending so much time initially to construct ilAssemblyRefs which is only used by GetReferencedAssemblies() call
- Avoid looping 120 libraries through on most cases: Often convTypeRef is called to get some very basic base-type like a "System.Object" or "System.Int32" thus going through the dependency assemblies one-by-one can be a fall-back method rather than default implementation.
I would love to have some benchmark tests for ProvidedTypes.fs but the issue is that it's mostly used by FSharp.Compiler via a heavy IDE, and current unit-tests are not covering the majority of the process, so I don't have any idea how that could be done. Right now the best way seems to be to …
> Minor perf opt
